Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
	at MJ.Run.interpret(Unknown Source)
	at MJ.Run.main(Unknown Source)
True
